# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: 'release'
    cancel-in-progress: false

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        permissions:
            contents: write
            packages: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: ./.github/actions/setup
            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npm config set "//npm.pkg.github.com/:_authToken" "${{ secrets.NPM_TOKEN }}"
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  echo "${{ secrets.GH_TOKEN }}"
            - run: npm run build
            - run: export GITHUB_TOKEN="${{ secrets.GH_TOKEN }}" && pnpm semantic-release
